name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "Bucket Name"
        required: true
        type: string

      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure Terraform Cloud
        run: |
          cat > ~/.terraformrc <<EOF
          credentials "app.terraform.io" {
            token = "${{ secrets.TF_API_TOKEN }}"
          }
          EOF

      - name: Terraform Init
        working-directory: ./s3
        run: terraform init


      - name: Terraform Plan
        working-directory: ./s3
        run: |
          terraform plan \
            -var="bucket_name=${{ github.event.inputs.bucket_name }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}"

      - name: Terraform Apply
        working-directory: ./s3
        run: |
          terraform apply -auto-approve \
            -var="bucket_name=${{ github.event.inputs.bucket_name }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}"
